### ISSUE TITLE
ImportError: cannot import name image_resizing

### ISSUE THREAD

**Issue by skielosky** [reddit/reddit#1324]
Warning: g.media_domain == g.domain. This may give untrusted content access to user cookies
Warning: g.oauth_domain == g.domain. CORS requests to g.domain will be allowed
Overriding g.--plugin to r2
edc277da-1805-cc4b-b09e-b7032454e544:1783 started f4325ab at 01:19:43 (took 1.74s)
Traceback (most recent call last):
  File "/usr/bin/paster", line 4, in <module>
    command.run()
  File "/usr/lib/python2.7/dist-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/python2.7/dist-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/python2.7/dist-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/home/ubuntu/src/reddit/r2/r2/commands.py", line 96, in command
    tresponse = test_app.get('/_test_vars')
  File "/usr/lib/python2.7/dist-packages/paste/fixture.py", line 208, in get
    return self.do_request(req, status=status)
  File "/usr/lib/python2.7/dist-packages/paste/fixture.py", line 389, in do_request
    **req.environ)
  File "/usr/lib/python2.7/dist-packages/paste/wsgilib.py", line 343, in raw_interactive
    app_iter = application(basic_environ, start_response)
  File "/usr/lib/python2.7/dist-packages/paste/lint.py", line 170, in lint_app
    iterator = application(environ, start_response_wrapper)
  File "/usr/lib/python2.7/dist-packages/paste/registry.py", line 379, in __call__
    app_iter = self.application(environ, start_response)
  File "/usr/lib/pymodules/python2.7/pylons/wsgiapp.py", line 116, in __call__
    self.setup_app_env(environ, start_response)
  File "/home/ubuntu/src/reddit/r2/r2/config/middleware.py", line 430, in setup_app_env
    self.load()
  File "/home/ubuntu/src/reddit/r2/r2/config/middleware.py", line 437, in load
    self.load_controllers()
  File "/home/ubuntu/src/reddit/r2/r2/config/middleware.py", line 458, in load_controllers
    controllers.load_controllers()
  File "/home/ubuntu/src/reddit/r2/r2/controllers/__init__.py", line 42, in load_controllers
    from listingcontroller import ListingController
  File "/home/ubuntu/src/reddit/r2/r2/controllers/listingcontroller.py", line 26, in <module>
    from oauth2 import require_oauth2_scope
  File "/home/ubuntu/src/reddit/r2/r2/controllers/oauth2.py", line 31, in <module>
    from reddit_base import RedditController, MinimalController, require_https
  File "/home/ubuntu/src/reddit/r2/r2/controllers/reddit_base.py", line 48, in <module>
    from r2.lib import filters, pages, utils, hooks, ratelimit
  File "/home/ubuntu/src/reddit/r2/r2/lib/pages/__init__.py", line 23, in <module>
    from pages import *
  File "/home/ubuntu/src/reddit/r2/r2/lib/pages/pages.py", line 120, in <module>
    from r2.lib.providers import image_resizing
ImportError: cannot import name image_resizing

**Comment by rrmckinley** [comment]
@xiongchiamiov can you please open source the image_resizing provider or otherwise solve this?

**Comment by rrmckinley** [comment]
@skielosky Sorry that the public repo is broken. If you like, you can move your git repo back before this breaking change. From the `src/reddit` dir run `git checkout b2075d49c96df5ac03ce655d8d550169b7efcf92`. When this problem is resolved, you can move back to HEAD.

**Comment by xiongchiamiov** [comment]
Ah dang, I forgot about the import.

I had this queued up, but hadn't pulled the trigger yet.  It's now [available](https://github.com/reddit/reddit/compare/2f7837e826cd0be34eabbb1975578545e5f5631c...df671653f2f6b781c08659372be27d765e7598f1), which should fix your import error.
