### ISSUE TITLE
install-reddit.sh does not create the initial admin account

### ISSUE THREAD

**Issue by 13steinj** [reddit/reddit#1570]
At some point between bc74b3205a2b32e0288f26bc1961d12c6d653c10 (I'm assuming, I don't really know, I'm not a shell script kind of guy) and now, install-reddit.sh no longer makes the initial administrator account (under normal circumstances "reddit" with password "password") and it has to be made manually.

    robin@ubuntu:~$ sudo reddit-shell
    Warning: g.media_domain == g.domain. This may give untrusted content access to user cookies
    Warning: g.oauth_domain == g.domain. CORS requests to g.domain will be allowed
    Overriding g.--plugin to r2
    ubuntu:26619 started ae687a6 at 08:40:38 (took 0.25s)
    Pylons Interactive Shell
    Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
    [GCC 4.8.2]
    
      All objects from r2.lib.base are available
      Additional Objects:
      mapper     -  Routes mapper object
      wsgiapp    -  This project's WSGI App instance
      app        -  paste.fixture wrapped around wsgiapp
    
    >>> from r2.models import Account
    >>> Account._byID(1)
    Traceback (most recent call last):
      File "<console>", line 1, in <module>
      File "/home/robin/src/reddit/r2/r2/lib/db/thing.py", line 411, in _byID
        raise NotFound, '%s %s' % (cls.__name__, missing)
    NotFound: Account [1]
    >>> from r2.models.account import register
    >>> admin_made = register('reddit', 'password', '127.0.0.1')
    >>> admin_made
    <Account 1>
    >>> admin_made.employee
    True
    >>> 

Keep in mind, "reddit" is in the dev config labeled as an admin (I didn't add that manually.)

**Comment by spladug** [comment]
This gets created by the test data injector. Is that not running for you?

**Comment by jinumm** [comment]
yes that injector is running smoothly , thanbs for the [web development ](http://www.appzincgroup.com)codes
