### ISSUE TITLE
Not Found for: r2 (did you run python setup.py develop?)

### ISSUE THREAD

**Issue by adrianevs** [reddit/reddit#1578]
Hy,

I get an error due the automatic instalation on reddit. I will paste here the last lines in terminal:

Traceback (most recent call last):
  File "/usr/bin/paster", line 4, in <module>
    command.run()
  File "/usr/lib/python2.7/dist-packages/paste/script/command.py", line 93, in run
    commands = get_commands()
  File "/usr/lib/python2.7/dist-packages/paste/script/command.py", line 135, in get_commands
    plugins = pluginlib.resolve_plugins(plugins)
  File "/usr/lib/python2.7/dist-packages/paste/script/pluginlib.py", line 82, in resolve_plugins
    pkg_resources.require(plugin)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: httpagentparser==1.7.8: Not Found for: r2 (did you run python setup.py develop?)
oneprovider@dedi-fr-20388:~$ 

How I can fix it ?

Thanks 👍

**Comment by kjoconnor** [comment]
This was at the end of the `install` script?

**Comment by adrianevs** [comment]
I solve it I get an answer [here](http://stackoverflow.com/questions/36564817/did-you-run-python-setup-py-develop/36564851?noredirect=1#comment60730003_36564851)

But I'm not sure if all is ok now, I get the final message where it say that reddit was installed but I do not understand how I can access reddit now.

**Comment by adrianevs** [comment]
Ok, I'm out of Reddit I really don't understand how's work
