### ISSUE TITLE
[BUG?] AttributeError: 'module' object has no attribute 'with_root_span'

### ISSUE THREAD

**Issue by hoang6** [reddit/reddit#1594]
I managed to install reddit on Digital Ocean without any problem, but when I try with AWS, I run into this. Does anybody know how to fix this? Thanks!

Traceback (most recent call last):
  File "/usr/bin/paster", line 4, in <module>
    command.run()
  File "/usr/lib/python2.7/dist-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/python2.7/dist-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/python2.7/dist-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/home/ubuntu/src/reddit/r2/r2/commands.py", line 72, in command
    tresponse = test_app.get('/_test_vars')
  File "/usr/lib/python2.7/dist-packages/paste/fixture.py", line 205, in get
    return self.do_request(req, status=status)
  File "/usr/lib/python2.7/dist-packages/paste/fixture.py", line 386, in do_request
    **req.environ)
  File "/usr/lib/python2.7/dist-packages/paste/wsgilib.py", line 343, in raw_interactive
    app_iter = application(basic_environ, start_response)
  File "/usr/lib/python2.7/dist-packages/paste/lint.py", line 169, in lint_app
    iterator = application(environ, start_response_wrapper)
  File "/home/ubuntu/src/reddit/r2/r2/config/middleware.py", line 432, in __call__
    return self.app(environ, safe_start_response)
  File "/home/ubuntu/src/reddit/r2/r2/config/middleware.py", line 307, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/paste/cascade.py", line 130, in __call__
    return self.apps[-1](environ, start_response)
  File "/usr/lib/python2.7/dist-packages/paste/registry.py", line 379, in __call__
    app_iter = self.application(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/paste/recursive.py", line 84, in __call__
    return self.application(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/paste/errordocument.py", line 196, in __call__
    app_iter = self.application(environ, change_response)
  File "/usr/lib/python2.7/dist-packages/weberror/evalexception.py", line 235, in __call__
    return self.respond(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/weberror/evalexception.py", line 418, in respond
    return self.application(environ, start_response)
  File "/home/ubuntu/src/reddit/r2/r2/config/middleware.py", line 184, in __call__
    return self.app(environ, start_response)
  File "/home/ubuntu/src/reddit/r2/r2/config/middleware.py", line 293, in __call__
    return self.app(environ, start_response)
  File "/home/ubuntu/src/reddit/r2/r2/config/middleware.py", line 252, in __call__
    return self.app(environ, start_response)
  File "/home/ubuntu/src/reddit/r2/r2/config/middleware.py", line 266, in __call__
    return self.app(environ, start_response)
  File "/home/ubuntu/src/reddit/r2/r2/config/middleware.py", line 386, in __call__
    return self.app(environ, start_response)
  File "/home/ubuntu/src/reddit/r2/r2/config/middleware.py", line 412, in __call__
    return self.app(environ, custom_start_response)
  File "/usr/lib/python2.7/dist-packages/routes/middleware.py", line 131, in __call__
    response = self.app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/pylons/wsgiapp.py", line 94, in __call__
    self.setup_app_env(environ, start_response)
  File "/home/ubuntu/src/reddit/r2/r2/config/middleware.py", line 449, in setup_app_env
    self.load()
  File "/home/ubuntu/src/reddit/r2/r2/config/middleware.py", line 456, in load
    self.load_controllers()
  File "/home/ubuntu/src/reddit/r2/r2/config/middleware.py", line 478, in load_controllers
    self.config['r2.plugins'].load_controllers()
  File "/home/ubuntu/src/reddit/r2/r2/lib/plugin.py", line 158, in load_controllers
    plugin.load_controllers()
  File "/home/ubuntu/src/liveupdate/reddit_liveupdate/__init__.py", line 198, in load_controllers
    from reddit_liveupdate.controllers import (
  File "/home/ubuntu/src/liveupdate/reddit_liveupdate/controllers.py", line 186, in <module>
    class LiveUpdatePixelController(BaseController):
  File "/home/ubuntu/src/liveupdate/reddit_liveupdate/controllers.py", line 202, in LiveUpdatePixelController
    @baseplate_integration.with_root_span("liveupdatepixelcontroller.GET_pixel")
AttributeError: 'module' object has no attribute 'with_root_span'

**Comment by scowcron** [comment]
I'm running into this on DO, i don't think it's specific to AWS

**Comment by hoang6** [comment]
I saw that new commit for controllers.py in liveupdate  (which is the culprit here) dated only 2 days ago. I installed reddit on DO last week, so this may be a bug.

**Comment by spladug** [comment]
Apologies, this is my fault. I've merged out e8a721635df9373d693b2b6053458ed6c41b9deb which should fix the issue.

**Comment by hoang6** [comment]
Thank you so much, spladug!
