### ISSUE TITLE
"Syntax error in JSON" - Edge doing JSON different?

### ISSUE THREAD

**Issue by indrora** [reddit/reddit#1605]
/u/indrora reporting for bug duty.

I use MSFT Edge, and on the current public build something gets funny. Sometimes, and I can't tell when, I can't reply/share/etc. Anything that pops DOM elements around makes Edge feel funny.

HOWEVER, that's not really the reason I'm here. The reason I'm here is that *somewhere* some nasty JSON is being passed over something else, and logs aren't being sent. 

Debug the debugger!

Here's the trace from Edge's console:

```
Error sending debug logs to server: parsererror ; SyntaxError: Syntax error
reddit-init.en.LAop1jXQoyk.js (5,26482)
   "Error sending debug logs to server:"
   "parsererror"
   ";"
   {
      [functions]: ,
      __proto__: {
         [functions]: ,
         __proto__: { },
         message: "",
         name: "SyntaxError"
      },
      description: "Syntax error",
      message: "Syntax error",
      name: "SyntaxError",
      number: -2146827286,
      stack: "SyntaxError: Syntax error
   at jQuery.parseJSON (https://www.redditstatic.com/reddit-init.en.LAop1jXQoyk.js:3:12571)
   at ajaxConvert (https://www.redditstatic.com/reddit-init.en.LAop1jXQoyk.js:1:10529)
   at S (https://www.redditstatic.com/reddit-init.en.LAop1jXQoyk.js:3:14280)
   at Anonymous function (https://www.redditstatic.com/reddit-init.en.LAop1jXQoyk.js:3:21239)"
   }
```

unfortunately, I don't have anything *better* than that.

**Comment by indrora** [comment]
Looking deeper, it looks like `/r2/r2/lib/js.py` is referring to `r.sendError(...)` where r.sendError hasn't been defined previously. [[1]](https://github.com/reddit/reddit/blob/218c89ba6af97717c552ff14fbba0063c17c13d8/r2/r2/lib/js.py#L433)

```
catch_errors = "try {{ {content} }} catch (err) {{ r.sendError('Error running module', '{name}', ':', err.toString()) }}"
```

shouldn't `/r2/r2/lib/js.py` refer to `r.logging.sendError(...)` instead?

**Comment by indrora** [comment]
BUMP nearly 1mo later.

**Comment by indrora** [comment]
bump again.

**Comment by 13steinj** [comment]
Bump or no bump, unfortunately these things take time. You can try posting to /r/bugs as a secondary.
