### ISSUE TITLE
Failure on app launch

### ISSUE THREAD

**Issue by kailan** [reddit/reddit#1815]
Error occurs when running `vagrant up` on a fresh instance with no changes.
Results in a 503 when attempting to access the application.

```
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Traceback (most recent call last):
==> default:   File "/usr/bin/paster", line 4, in <module>
==> default:     command.run()
==> default:   File "/usr/lib/python2.7/dist-packages/paste/script/command.py", line 104, in run
==> default:     invoke(command, command_name, options, args[1:])
==> default:   File "/usr/lib/python2.7/dist-packages/paste/script/command.py", line 143, in invoke
==> default:     exit_code = runner.run(args)
==> default:   File "/usr/lib/python2.7/dist-packages/paste/script/command.py", line 238, in run
==> default:     result = self.command()
==> default:   File "/home/ubuntu/src/reddit/r2/r2/commands.py", line 72, in command
==> default:     config_name, relative_to=here_dir, global_conf=global_conf)
==> default:   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
==> default:     return loadobj(APP, uri, name=name, **kw)
==> default:   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
==> default:     return context.create()
==> default:   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 710, in create
==> default:     return self.object_type.invoke(self)
==> default:   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 146, in invoke
==> default:     return fix_call(context.object, context.global_conf, **context.local_conf)
==> default:   File "/usr/lib/python2.7/dist-packages/paste/deploy/util.py", line 58, in fix_call
==> default:     reraise(*exc_info)
==> default:   File "/usr/lib/python2.7/dist-packages/paste/deploy/compat.py", line 23, in reraise
==> default:     exec('raise t, e, tb', dict(t=t, e=e, tb=tb))
==> default:   File "/usr/lib/python2.7/dist-packages/paste/deploy/util.py", line 55, in fix_call
==> default:     val = callable(*args, **kw)
==> default:   File "/home/ubuntu/src/reddit/r2/r2/__init__.py", line 41, in make_app
==> default:     return real_make_app(*args, **kwargs)
==> default:   File "/home/ubuntu/src/reddit/r2/r2/config/middleware.py", line 506, in make_app
==> default:     config = load_environment(global_conf, app_conf)
==> default:   File "/home/ubuntu/src/reddit/r2/r2/config/environment.py", line 69, in load_environment
==> default:     g = Globals(config, global_conf, app_conf, paths)
==> default:   File "/home/ubuntu/src/reddit/r2/r2/lib/app_globals.py", line 484, in __init__
==> default:     sample_rate=self.config.get("tracing_sample_rate"),
==> default: TypeError: 
==> default: configure_tracing() takes at least 2 arguments (1 given); got ({'takedo...'1'}, cache_dir=...), wanted (*args, **kwargs)
```

**Comment by rsd** [comment]
Same issue on a 14.04 clean install (lxc)

**Comment by epsv4** [comment]
i got the problem too

**Comment by Charles6666** [comment]
Dont let no one leave as there trying too if i bad too stay Well ill be and Will get too the bottem of this.

**Comment by Charles6666** [comment]
Yes i wont an agrément about this people be eraseing mine cash and then leave with there pretending To be me and trying to leave me untrue when ever ill be true .

**Comment by andrewkeithly** [comment]
I too am getting this error
