### ISSUE TITLE
Search where only search term is "youtube" never brings back results

### ISSUE THREAD

**Issue by ivanatpr** [reddit/reddit#1816]
Using the reddit's search box if you do a search for just "youtube", it doesn't produce search results. You don't ever get the "there doesn't seem to be anything here" message, just a mostly blank search results page. 

Adding in second search term seems to fix it even if you do something like "youtube -jhldjfhalksf" where the second search term probably isn't affecting the number of results. 

![screenshot of blank search results page](https://user-images.githubusercontent.com/2243835/26841946-1ca9ba88-4ab9-11e7-9021-01c997963eaf.png).

**Comment by lindhe** [comment]
I can confirm that it does so for me too.

**Comment by michael-lazar** [comment]
I discovered the same bug with the keyword "reddit", searching through the api actually returns invalid json.

https://api.reddit.com/r/all/search.json?q=reddit
```
"{}"
```

**Comment by kjoconnor** [comment]
Both `YouTube` and `reddit` are [stopwords](https://en.wikipedia.org/wiki/Stop_words) for us, as they end up in a huge number of documents and don't provide any real value without other identifiers. We may reevaluate this in the future when we switch to a new search provider under the hood, but for now, these don't work on purpose.

**Comment by michael-lazar** [comment]
You should at least consider making the api response consistent with other empty searches. This currently breaks a bunch of reddit clients and bots that are expecting json objects, including PRAW 4.5.1.

**Expected behavior - no results**
```python
>>> r.subreddit('all').search('ebnqwiebiquwybegqwybeqbddd').next()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/praw/models/listing/generator.py", line 79, in next
    return self.__next__()
  File "/usr/local/lib/python2.7/site-packages/praw/models/listing/generator.py", line 52, in __next__
    self._next_batch()
  File "/usr/local/lib/python2.7/site-packages/praw/models/listing/generator.py", line 70, in _next_batch
    raise StopIteration()
StopIteration
```

**Behavior with stop words or empty searches**
```python
>>> r.subreddit('all').search('').next()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/praw/models/listing/generator.py", line 79, in next
    return self.__next__()
  File "/usr/local/lib/python2.7/site-packages/praw/models/listing/generator.py", line 52, in __next__
    self._next_batch()
  File "/usr/local/lib/python2.7/site-packages/praw/models/listing/generator.py", line 72, in _next_batch
    if self._listing.after:
AttributeError: 'unicode' object has no attribute 'after'

>>> r.subreddit('all').search('reddit').next()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/praw/models/listing/generator.py", line 79, in next
    return self.__next__()
  File "/usr/local/lib/python2.7/site-packages/praw/models/listing/generator.py", line 52, in __next__
    self._next_batch()
  File "/usr/local/lib/python2.7/site-packages/praw/models/listing/generator.py", line 72, in _next_batch
    if self._listing.after:
AttributeError: 'unicode' object has no attribute 'after'
```

**Comment by kjoconnor** [comment]
Hmmm interesting - we'll check that out. Thanks!

**Comment by bsimpson63** [comment]
The api response issue should be fixed now, see https://www.reddit.com/search.json?q=reddit
