### ISSUE TITLE
Can't expand comments or create link/text posts on Firefox even with all extensions disabled. Console is complaining about missing functions.

### ISSUE THREAD

**Issue by sirisian** [reddit/reddit#1845]
I tried a few ways to submit this to /r/bugs, but it just redirects me to "page not found" when hitting submit. When I try to expand comments in the console it says:

    "Client Error: "TypeError: morechildren is not a function" thrown at L1:8 in https://www.reddit.com/r/IAmA/comments/6uvtsl/were_nasa_scientists_ask_us_anything_about/ Message: "TypeError: morechildren is not a function"" Object { tag: "unknown" }  reddit-init.en-us.n8r99GszUtw.js:5:27320
    Not sending debug log; already sent 3  reddit-init.en-us.n8r99GszUtw.js:5:26400
    "Client Error: "TypeError: click_thing is not a function" thrown at L1:1 in https://www.reddit.com/r/IAmA/comments/6uvtsl/were_nasa_scientists_ask_us_anything_about/ Message: "TypeError: click_thing is not a function"" Object { tag: "unknown" }  reddit-init.en-us.n8r99GszUtw.js:5:27320
    Not sending debug log; already sent 3  reddit-init.en-us.n8r99GszUtw.js:5:26400
    "Client Error: "TypeError: click_thing is not a function" thrown at L1:1 in https://www.reddit.com/r/IAmA/comments/6uvtsl/were_nasa_scientists_ask_us_anything_about/ Message: "TypeError: click_thing is not a function"" Object { tag: "unknown" }  reddit-init.en-us.n8r99GszUtw.js:5:27320
    Not sending debug log; already sent 3  reddit-init.en-us.n8r99GszUtw.js:5:26400
    "Client Error: "TypeError: click_thing is not a function" thrown at L1:1 in https://www.reddit.com/r/IAmA/comments/6uvtsl/were_nasa_scientists_ask_us_anything_about/ Message: "TypeError: click_thing is not a function"" Object { tag: "unknown" }  reddit-init.en-us.n8r99GszUtw.js:5:27320
    Not sending debug log; already sent 3  reddit-init.en-us.n8r99GszUtw.js:5:26400
    "Client Error: "TypeError: click_thing is not a function" thrown at L1:1 in https://www.reddit.com/r/IAmA/comments/6uvtsl/were_nasa_scientists_ask_us_anything_about/ Message: "TypeError: click_thing is not a function"" Object { tag: "unknown" }  reddit-init.en-us.n8r99GszUtw.js:5:27320
    Not sending debug log; already sent 3  reddit-init.en-us.n8r99GszUtw.js:5:26400
    TypeError: morechildren is not a function[Learn More]  were_nasa_scientists_ask_us_anything_about:1:8
    TypeError: click_thing is not a function[Learn More] were_nasa_scientists_ask_us_anything_about:1:1

When I click to create a link/text post it says:

    Error running module reddit.js : TypeError: this.$el.find(...).validator is not a function  reddit-init.en-us.n8r99GszUtw.js:5:27320
    TypeError: r.sendError is not a function[Learn More]  reddit-init.en-us.n8r99GszUtw.js:8:21489
    Loading failed for the <script> with source “https://www.redditstatic.com/moat/moatframe.js”.  submit:1
    TypeError: e.actions is undefined[Learn More]  newlink-media-upload.YdFn-ei5M5I.js:1:2567
    "Client Error: "TypeError: r.srAutocomplete is undefined" thrown at L57:31 in https://www.reddit.com/r/bugs/submit?selftext=true Message: "TypeError: r.srAutocomplete is undefined"" Object { tag: "unknown" }  reddit-init.en-us.n8r99GszUtw.js:5:27320
    JQMIGRATE: Migrate is installed with logging active, version 3.0.0  jquery_migrate.js:18:30
    [TBStorage]  tbplugins.js:20:13
    Domain: www  tbplugins.js:21:13
    TypeError: r.srAutocomplete is undefined[Learn More]  submit:57:31
    Error sending debug logs to server: error ; No Reason Phrase  reddit-init.en-us.n8r99GszUtw.js:5:27062
    debug information for browser

I've disabled all extensions and no change. Even hard refreshing does nothing. This started a few hours ago.

**Comment by sirisian** [comment]
Okay I found a solution, mentioned in other posts I linked, which was to delete all my cookies, not just reddit associated cookies. Apparently Reddit relies on a cookie that is not associated with reddit.com. I have thousands of cookies so I have no idea which one that was, but whatever it was it caused Reddit.com to throw the above errors. Googling online this bug is maybe rare. I'd look at how you use cookies since there's a bug with them someplace.

**Comment by maximusdominus** [comment]
I just came across this bug and resolved it: it appears to be caused by localStore running out of space.

I have a reddit chrome extension that was storing about 290,000 reddit post IDs in localStorage. After updating the extension logic to not store so much, the javascript works again. Collapsing comments was broken, sorting posts was also broken.

After filling localStorage up again, I got a quota exceeded error, and was then able to reproduce the other errors.

I don't believe this is a cookie issue, but telling your browser to clear cookies also happens to wipe out localStore. Disabling extensions wont work because localStore will still be full.
